package jetbrains.mps.samples.Shapes.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class RemoveSquare_QuickFix extends QuickFix_Runtime {
  public RemoveSquare_QuickFix() {
    super(new SNodePointer("r:e44eb14d-c2bb-4d65-bb30-217515d5e47a(jetbrains.mps.samples.Shapes.typesystem)", "1891605514471469616"));
  }
  public String getDescription(SNode node) {
    return "Remove the " + ((String) RemoveSquare_QuickFix.this.getField("colorName")[0]) + " square";
  }
  public void execute(SNode node) {
    SNodeOperations.deleteNode(node);
  }
}
